apiVersion: test
kind: Deployment
metadata:
  labels:
    app: rssant
  name: rssant
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rssant
  template:
    metadata:
      labels:
        app: rssant
    spec:
      containers:
        - image: swr.troila.com/python-test/python:test
          imagePullPolicy: IfNotPresent
          name: python-test
      restartPolicy: Always

